### ISSUE TITLE
Syntax error silently ignored on save with "format on save"

### ISSUE THREAD

**Issue by justindotpub** [JakeBecker/ide-elixir#3]
I'm running the latest elixir-ls and ide-elixir from git with Atom in dev mode on macos high sierra with format on save enabled.

If I remove a closing paren from a function and save, I notice my code isn't auto formatted but don't receive an error.  If I type command-shift-c to explicitly format I see the error "failed to format code"... "SyntaxError".

I don't know if this is an ide-elixir issue or atom-ide-ui, but I thought I'd start here.

**Comment by JakeBecker** [comment]
This looks like a deliberate decision by the https://github.com/atom/atom-languageclient/ library. Regardless of whether it was triggered manually or automatically, ElixirLS responds to the format request with that syntax error. I guess they thought showing the error was too obtrusive for something triggered automatically on save. I'm inclined to agree with that decision, but feel free to give them your thoughts.

One thing that might improve the UX though would be to show syntax errors immediately instead of waiting for project compilation. We have to wait for the file to be saved to compile it, but we could syntax-check it immediately as the user types. If there are errors visible, it might make it more intuitive why the formatting failed.

**Comment by justindotpub** [comment]
That makes sense.  The lack of any visible indication as to what the problem was combined with no reformatting is what was confusing.  I'll see if there's some way to get feedback on syntax without being too obtrusive.  Thanks for the reply.
